### 단축 URL 생성
POST http://localhost:8080/shorten-url
Content-Type: application/json

{
  "originURL": "https://wwws.naver.com",
  "ttlMinutes": 10
}

> {%
    client.global.set("shortenedUrl", response.body.shortenedUrl);
%}

### 원본 URL 조회
GET http://localhost:8080/shorten-url/{{shortenedUrl}}