drop all objects; -- only h2
create table shortened_url
(
    id bigint generated by default as identity,
    origin_url varchar(255) not null,
    shortened_url varchar(100) not null,
    expired_at TIMESTAMP,
    disabled BOOLEAN DEFAULT FALSE not null
);

create table blocked_domain
(
    id bigint generated by default as identity,
    domain varchar(255) not null
)