spring:
  application:
    name: onem-backend
  datasource:
    url: jdbc:postgresql://ep-withered-violet-a157m6c0.ap-southeast-1.pg.koyeb.app/koyebdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
