spring:
  application:
    name: onem-backend
server:
  tomcat:
    mbeanregistry:
      enabled: true
  forward-headers-strategy: native
  address: 0.0.0.0



management:
  info:
    java:
      enabled: true
    os:
      enabled: true
  server:
    port: 8080 #편의를 위해
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-components: always
      show-details: always




