CREATE TABLE IF NOT EXISTS BLOCKED_DOMAIN
(
    ID     UUID PRIMARY KEY,
    DOMAIN VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS SHORTENED_URL
(
    ID         VARCHAR(255) PRIMARY KEY,
    ORIGIN_URL VARCHAR(255) NOT NULL,
    EXPIRED_AT TIMESTAMP    NOT NULL,
    DELETED    BOOLEAN DEFAULT FALSE
);
