### Origin URL 저장
POST {{baseUrl}}/shorten-url/create
Content-Type: application/json

{
  "originUrl": "https://www.naver.com"
}

### 짧은 키워드로 Origin URL 조회
POST {{baseUrl}}/shorten-url/search
Content-Type: application/json

{
  "shortenUrl": "local1"
}
