### Origin URL 저장
POST {{baseUrl}}/shorten-url/create
Content-Type: application/json

{
  "originUrl": "https://www.naver1.com"
}

### 짧은 키워드로 Origin URL 조회
POST {{baseUrl}}/shorten-url/search
Content-Type: application/json

{
  "shortenUrl": "dev -9c5cd5ae-72d3-4f4d-a8a8-b34c2dd42443"
}
