global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['shortenurl:8080']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
